// Minimal C++ adapter. The HybridObject's native surface is generated by
// Nitrogen (see ../nitrogen/generated/); this file only exists so the CMake
// target has at least one source file to compile. Real cross-platform C++
// logic would live here, but LayoutDirection is a thin Kotlin/Swift wrapper
// over React Native's own i18n utilities — no shared C++ is needed.
#include <jni.h>

extern "C" JNIEXPORT void JNICALL
Java_com_margelo_nitro_layoutdirection_LayoutDirection_noop(JNIEnv*, jobject) {}
